baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ck3g.githib.io"

template:
  title: Today I Learnt
  avatar: avatar.png
  gravatar: "809ac34c7d3f932baf08bba11c486b9a"
  description: "A website with blog posts about what I've learnt today"

  # Header and footer text
  # header_text: >
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: 'Vitaly.Tatarintsev@gmail.com'
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "ck3g"
  google_plus:
  instagram:
  linkedin: 'https://my.linkedin.com/pub/vitaly-tatarintsev/40/aa9/496'
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: 'http://stackexchange.com/users/56019/ck3g'
  steam:
  tumblr:
  twitter: "ck3g"
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-65603547-1"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
